name: flutter_tes
version: 1.0.0+1
publish_to: none
description: tes flutter
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  http: ^0.13.4
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/

